# STAT 340 Lecture 14：线性回归（Modeling II）

**讲师：** Yongyi Guo  
**课程：** STAT 340 Data Science Modeling II (002)

---

## 学习目标

1. 理解简单线性回归（Simple Linear Regression, SLR）和多元线性回归的含义
2. 使用 R 对给定数据集运行线性回归，并解读系数估计结果
3. 理解对估计系数关联 p 值的含义

---

## 一、简单线性回归模型

### 1.1 模型定义

简单线性回归建模的是 $Y$ 在给定 $X$ 条件下的分布：

$$Y = \beta_0 + \beta_1 X + \epsilon$$

给定数据集 $D = \{(x_i, y_i)\}_{i=1}^n$，每个观测满足：

$$y_i = \beta_0 + \beta_1 x_i + \epsilon_i$$

其中：
- $x_i$ 可以视为**固定的**（非随机的）——我们条件化在 $x$ 上，所以 $x$ 没有随机性
- $\beta_0$（截距）和 $\beta_1$（斜率）是**未知模型参数**（回归系数），描述了"信号部分"即回归直线
- $\epsilon_i$ 是**误差项**（噪声），包含了所有 $X$ 无法解释 $Y$ 的部分（例如数据中未出现的其他变量）
- $\sigma^2$ 是**噪声方差**，也是未知模型参数

> **老师补充：** $\epsilon_i$ 是每个数据点特有的噪声。模型中唯一的随机性来源就是 $\epsilon_i$。即使 $Y$ 还可能依赖于其他变量，这些其他因素都被吸收到 $\epsilon_i$ 中了。

### 1.2 模型假设

| 假设 | 内容 | 说明 |
|------|------|------|
| **线性性** | $\mathbb{E}[Y \mid X = x] = \beta_0 + \beta_1 x$ | 条件期望是 $X$ 的线性函数 |
| **独立性** | $\{\epsilon_i\}_{i=1}^n$ 是独立的随机变量序列 | 每个数据点的噪声彼此独立 |
| **同方差性** | $\text{Var}(Y_i \mid X_i) = \sigma^2$，对所有 $i$ 恒成立 | 噪声的变异程度在所有 $x$ 值上保持恒定 |
| **正态误差（可选）** | $\epsilon_i \sim N(0, \sigma^2)$ 或等价地 $Y_i \mid X_i \sim N(\beta_0 + \beta_1 X_i, \sigma^2)$ | 更强的假设，便于后续推断；不一定总需要 |

> **老师补充：** 基本假设是 $\epsilon_i$ iid、均值为 0、方差为 $\sigma^2$。正态性假设更强但更方便做推断。有时需要正态性，有时不需要。

---

## 二、最小二乘估计（Least Squares Estimation）

### 2.1 核心思想

给定散点图数据，我们要找一条直线，使它尽可能"接近"所有数据点。具体做法是最小化**残差平方和（RSS / SSE）**：

$$(\hat{\beta}_0, \hat{\beta}_1) = \arg\min_{\beta_0, \beta_1} \sum_{i=1}^{n} (Y_i - \beta_0 - \beta_1 X_i)^2 := Q(\beta_0, \beta_1)$$

**残差（Residual）**的定义：

$$e_i = y_i - \hat{y}_i = y_i - (\hat{\beta}_0 + \hat{\beta}_1 x_i)$$

残差 $e_i$ 就是每个数据点到拟合回归线的**垂直距离**。我们希望所有残差都很小，所以最小化它们的平方和。

> **老师补充：** 把 $x_i, y_i$ 视为已知和固定的，这个损失函数是关于 $\beta_0, \beta_1$ 的二次函数。对它分别关于 $\beta_0$ 和 $\beta_1$ 求偏导、令偏导为零，就能求解。

### 2.2 解析解

对损失函数求导并令其为零，得到：

$$\hat{\beta}_1 = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n}(x_i - \bar{x})^2}$$

$$\hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x}$$

> **关键理解：** $\hat{\beta}_0$ 和 $\hat{\beta}_1$ 是 $x_i$ 和 $y_i$ 的**函数**，它们是**统计量**，也是回归系数的**点估计量**。

---

## 三、解读估计值

### 3.1 解读 $\hat{\beta}_1$（斜率）

将 $\hat{\beta}_1$ 的分子分母同除以 $\frac{1}{n}$：

$$\hat{\beta}_1 = \frac{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2}$$

定义**（未校正的）样本方差**：

$$s_x^2 = \frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2, \quad s_y^2 = \frac{1}{n}\sum_{i=1}^{n}(y_i - \bar{y})^2$$

定义**样本相关系数**：

$$\hat{\rho}_{x,y} = \frac{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sqrt{s_x^2 \cdot s_y^2}} = \frac{\frac{1}{n}\sum(x_i - \bar{x})(y_i - \bar{y})}{s_x \cdot s_y}$$

则可以推导出：

$$\boxed{\hat{\beta}_1 = \frac{s_y}{s_x} \cdot \hat{\rho}_{x,y}}$$

**核心解读：斜率 = 标准差之比 × 样本相关系数**

> **老师补充：**
> - $s_y / s_x$ 部分的作用是**单位转换**。例如 $Y$ 的单位是"美元/年"，$X$ 的单位是"受教育年数"，则 $s_y / s_x$ 的单位就是"（美元/年）/（受教育年数）"，保证 $\hat{\beta}_1 \cdot x_i$ 与 $y_i$ 单位一致。
> - $\hat{\rho}_{x,y}$ 部分是无量纲的归一化度量（-1 到 1 之间），衡量 $X$ 和 $Y$ 的线性相关程度。如果 $X$ 和 $Y$ 高度相关，$\hat{\beta}_1$ 中的"信号"就多；如果完全不相关（$\hat{\rho} \approx 0$），说明用 $X$ 预测 $Y$ 很难找到信号。

**特殊情况：** 当预测变量和响应变量完全相关（$\hat{\rho}_{x,y} = 1$，所有点精确在一条直线上，无抖动）时：

$$\hat{\beta}_1 = \frac{s_y}{s_x}$$

### 3.2 解读 $\hat{\beta}_0$（截距）

$$\hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x}$$

**含义：** 一旦确定了斜率 $\hat{\beta}_1$，调整截距就是将回归线上下平移，找到最优位置。

**关键性质：** 回归线**始终经过数据的中心点** $(\bar{x}, \bar{y})$。

> **老师补充：** 这很直观——我们已固定斜率，上下平移回归线，最优选择就是让它通过数据点云的中心 $(\bar{x}, \bar{y})$。这样看起来是最好的拟合。

---

## 四、$\hat{\beta}_1$ 的方差

### 4.1 推导

$$\text{Var}(\hat{\beta}_1) = \text{Var}\left(\frac{\sum_i (x_i - \bar{x})y_i}{\sum_i (x_i - \bar{x})^2}\right)$$

将 $y_i = \beta_0 + \beta_1 x_i + \epsilon_i$ 代入，注意到 $x_i$ 是固定的（非随机的），唯一的随机性来自 $\epsilon_i$：

$$= \text{Var}\left(\frac{\sum_i (x_i - \bar{x})\epsilon_i}{\sum_i (x_i - \bar{x})^2}\right)$$

利用 $\epsilon_i$ 独立且 $\text{Var}(\epsilon_i) = \sigma^2$，以及 $\text{Var}(cX) = c^2 \text{Var}(X)$：

$$= \frac{\sum_i (x_i - \bar{x})^2 \cdot \text{Var}(\epsilon_i)}{\left(\sum_i (x_i - \bar{x})^2\right)^2} = \boxed{\frac{\sigma^2}{\sum_i (x_i - \bar{x})^2}}$$

### 4.2 直觉理解

影响 $\hat{\beta}_1$ 不确定性的因素：

1. **$\sigma^2$ 越大** → 方差越大：原始数据噪声大，对回归线的估计就越不确定
2. **$\sum(x_i - \bar{x})^2$ 越大**（即 $X$ 的样本方差越大）→ 方差越小：$X$ 越分散/多样化，我们对不同 $X$ 值下 $Y$ 的表现有更多信息，估计就越精确

> **老师补充：** 如果数据集信息更丰富（$X$ 的分布更广泛），我们的不确定性就会下降。

---

## 五、R 实战：铅含量与暴力犯罪

### 5.1 背景

- 1920 年代 Thomas Midgley Jr. 发现在汽油中添加四乙基铅（tetraethyllead）可以减少发动机爆震
- 然而燃烧四乙基铅导致大气中铅含量急剧升高
- 1950–70 年代，研究者开始怀疑大气铅含量升高会导致广泛的铅中毒（抑郁、食欲减退、认知障碍）
- 更近年的争议性理论认为：铅暴露（大气中或老建筑油漆中）与日后暴力犯罪发生率相关

跨国数据（美国、英国、加拿大、澳大利亚等）显示：血铅水平与入室盗窃率、抢劫率、严重攻击率之间存在**视觉上的相关性**。

### 5.2 数据集

数据集包含美国多个城市的大气铅含量（单位：公吨）和 **22 年后**的严重攻击率（单位：每百万人）。

```r
lead <- read.csv('lead.csv')
head(lead)
##      city air.pb.metric.tons aggr.assault.per.million
## 1 Atlanta              421                     1029
## 2 Atlanta              429                      937
## 3 Atlanta              444                      887
## ...
```

包含的城市：Atlanta, Chicago, Indianapolis, Minneapolis, New Orleans, San Diego。

> **老师补充：** 不同城市可能有不同的铅含量水平和人口特征，所以我们先聚焦于单个城市 Atlanta，理解攻击率如何依赖于大气铅含量。

### 5.3 散点图观察

以 Atlanta 数据画散点图（X = 铅含量，Y = 攻击率）：
- 视觉上**有明显的线性趋势**
- 但在低铅含量区域，数据在 $Y$ 方向上似乎更加分散（方差较大），而高铅含量区域更集中
- 这可能**稍微违反同方差性假设**，但后续诊断表明不算严重

### 5.4 在 R 中拟合线性模型

使用 `lm()` 函数（lm = linear model）：

```r
# 语法：lm(y ~ 1 + x, data = dframe)
# "1" 表示截距项（可省略，R 默认包含）
# "~" 左边是响应变量 Y，右边是预测变量 X

atlanta_lead_lm <- lm(aggr.assault.per.million ~ 1 + air.pb.metric.tons,
                      data = atlanta_lead)
summary(atlanta_lead_lm)
```

### 5.5 解读 `summary()` 输出

```
## Coefficients:
##                     Estimate Std. Error t value  Pr(>|t|)
## (Intercept)        107.94276   80.46409   1.342    0.189
## air.pb.metric.tons   1.40375    0.08112  17.305   <2e-16 ***
## ---
## Residual standard error: 180.6 on 34 degrees of freedom
## Multiple R-squared: 0.898,  Adjusted R-squared: 0.895
## F-statistic: 299.4 on 1 and 34 DF,  p-value: < 2.2e-16
```

**逐行解读：**

| 部分 | 含义 |
|------|------|
| **Call** | 显示你调用的具体 `lm()` 函数，确认拟合的模型 |
| **Residuals** | 所有残差 $e_i$ 的汇总统计（最小值、Q1、中位数、Q3、最大值） |
| **Estimate 列** | $\hat{\beta}_0 = 107.94$（截距），$\hat{\beta}_1 = 1.40$（斜率） |
| **Std. Error 列** | 估计值的标准误差（标准化因子） |
| **t value 列** | t 统计量 = Estimate / Std. Error |
| **Pr(>\|t\|) 列** | 对应假设检验的 p 值 |

**系数解读：**

- **$\hat{\beta}_1 = 1.40$**：在 Atlanta，大气铅含量**每增加 1 公吨**，22 年后的严重攻击率**平均增加约 1.4 次/百万人**
- **$\hat{\beta}_0 = 107.94$**：模型预测如果大气中**完全没有铅**，仍会有约 108 次严重攻击/百万人

提取系数的另一种方式：

```r
atlanta_lead_lm$coefficients
##      (Intercept) air.pb.metric.tons
##       107.942757           1.403746
```

---

## 六、模型诊断

> **老师强调：** 对任何数据集，你都可以拟合线性模型——即使 $y = x^2$ 你也能做。但如果数据不满足 SLR 假设，输出结果就没有意义。所以拟合之后要立即检查模型假设是否合理。

### 6.1 检查同方差性（Homoscedasticity）

**方法：** 绘制残差 vs. 拟合值图

```r
plot(atlanta_lead_lm, which=1)  # 第 1 种诊断图
```

**理想情况：** 残差在不同拟合值处的变异程度恒定，散点均匀分布在 $y=0$ 水平线周围，呈矩形散布形态。

**本例结果：** 
- 较小铅含量（较小拟合值）对应的残差方差**略高**，且略偏正值
- 较大铅含量处方差较小
- 但总体来看**偏离不算极端**，可以接受

> **老师补充：** 模型诊断类似于假设检验，但我们不是"接受"模型，而是检查数据是否"显著偏离"模型假设。只要诊断图没有太极端的偏离，就认为是可以的。在实际应用中，需要根据具体场景决定对偏离的容忍程度。

### 6.2 检查残差正态性

**方法 1：** 残差直方图

```r
resids <- residuals(atlanta_lead_lm)
hist(resids)
```

**方法 2：** Q-Q 图（更精确）

```r
plot(atlanta_lead_lm, which=2)  # 第 2 种诊断图
```

**理想情况：** 标准化残差 vs. 理论正态分位数应落在同一条直线上。

**本例结果：** 有轻微偏离（尾部稍重），但不极端。

**对比例子：** 老师演示了从 $t$ 分布（df=3）生成数据后做 Q-Q 图的效果——尾部偏离非常明显，与我们的残差 Q-Q 图相比，我们的数据偏离正态不算严重。

---

## 七、回归系数的假设检验与置信区间

### 7.1 检验 $\beta_1$ 是否显著

**问题：** 铅含量和攻击率之间的关联是"真实的"吗？即 $X$ 是否显著影响 $Y$？

$$H_0: \beta_1 = 0 \quad \text{vs} \quad H_1: \beta_1 \neq 0$$

- $H_0$：$X$ 对 $Y$ 没有效应（斜率为零）
- $H_1$：$X$ 对 $Y$ 有效应

> **注意：** 这里的"效应"是**关联意义**上的，不是因果意义上的。

**假设检验步骤：**

1. **构造检验统计量：** t 统计量（$\hat{\beta}_1$ 的标准化版本）= $\hat{\beta}_1$ / Std. Error
2. **零假设下的分布：** $t_{n-2}$ 分布
3. **计算 p 值：** 衡量观测数据的极端程度
4. **拒绝准则：** p 值小于显著性水平则拒绝 $H_0$

**本例结果：**
- $\hat{\beta}_1$ 的 t 值 = 17.305，p 值 < $2 \times 10^{-16}$（三颗星 `***`）
- **结论：** 强烈拒绝 $H_0$，铅含量与攻击率之间存在统计上高度显著的关联

> **老师补充：** 如果假设正态噪声，p 值是精确的；如果噪声非正态，p 值是渐近的（当 $n$ 足够大时仍然有效）。

### 7.2 检验 $\hat{\beta}_0$ 是否显著

对截距同样可以检验 $H_0: \beta_0 = 0$（即回归线是否过原点）：
- t 值 = 1.342，p 值 = 0.189
- **未拒绝 $H_0$**：截距与 0 无显著差异

### 7.3 置信区间

```r
confint(atlanta_lead_lm, level=0.95)
##                        2.5 %      97.5 %
## (Intercept)        -55.579958  271.465472
## air.pb.metric.tons   1.238891    1.568602
```

**解读：**
- 截距的 95% CI 包含 0（与 p 值 = 0.189 一致，不显著）
- 斜率的 95% CI 为 [1.24, 1.57]，**不包含 0**（与 p 值 < $2 \times 10^{-16}$ 一致，显著）

**规律：** 效应显著 ⟺ p 值小 ⟺ 置信区间不覆盖 0

---

## 八、利用模型做预测

### 8.1 插值预测（合理）

**问题：** 若 Atlanta 大气铅含量为 1300 公吨，预测 22 年后攻击率？

```r
predict(atlanta_lead_lm, newdata=data.frame(air.pb.metric.tons=1300))
## 1932.813
```

1300 在观测数据范围内，预测结果约 1933 次/百万人，合理。

### 8.2 外推预测（需谨慎！）

**问题：** 若铅含量升到 2000 公吨呢？

2000 公吨**远超观测数据范围**（数据中最大约 1500）。**预测的可靠性会随着远离数据范围而下降**。

> **老师提醒：** 线性趋势在观测范围内可能成立，但外推到数据范围之外时，真实关系可能不再是线性的。这是一个很重要的实践教训。

---

## 九、评估模型拟合度

### 9.1 残差平方和（RSS / SSE）

$$\text{RSS} = \text{SSE} = \sum_{i=1}^{n} e_i^2 = \sum_{i=1}^{n}(y_i - \hat{y}_i)^2$$

### 9.2 决定系数 $R^2$

$$R^2 = \frac{\text{TSS} - \text{RSS}}{\text{TSS}} = 1 - \frac{\text{RSS}}{\text{TSS}}$$

其中总平方和：

$$\text{TSS} = \sum_{i=1}^{n}(y_i - \bar{y})^2$$

**解读：** $R^2$ 衡量 $Y$ 的变异中有多少比例可以被 $X$ 的变异解释（0 到 1 之间）。

在简单线性回归中：$R^2 = r^2$（样本相关系数的平方）。

**本例结果：** $R^2 = 0.898$，说明约 89.8% 的攻击率变异可被铅含量的变异解释，拟合效果很好。

### 9.3 F 统计量

F 统计量 = 299.4（1 和 34 自由度），p 值 < $2.2 \times 10^{-16}$，检验**模型整体显著性**（即 $H_0: \beta_1 = 0$）。在简单线性回归中，F 检验和 t 检验等价。

---

## 十、关键 R 函数速查

| 函数 | 用途 |
|------|------|
| `lm(y ~ x, data=df)` | 拟合线性模型 |
| `summary(model)` | 查看完整汇总（系数、p 值、$R^2$ 等） |
| `model$coefficients` | 提取回归系数 |
| `residuals(model)` | 提取残差 $e_i$ |
| `fitted(model)` | 提取拟合值 $\hat{y}_i$ |
| `plot(model, which=1)` | 残差 vs. 拟合值图（检查同方差性） |
| `plot(model, which=2)` | 正态 Q-Q 图（检查正态性） |
| `confint(model, level=0.95)` | 系数的 95% 置信区间 |
| `predict(model, newdata=...)` | 对新数据做预测 |

---

## 十一、本讲要点总结

1. **简单线性回归**建模 $Y$ 对 $X$ 的条件分布，假设线性关系 + iid 噪声
2. **最小二乘法**通过最小化残差平方和来拟合回归线，有闭式解
3. **$\hat{\beta}_1$** 可以分解为标准差之比乘以样本相关系数，直观理解为"单位转换 × 相关性强度"
4. **回归线始终过中心点** $(\bar{x}, \bar{y})$
5. **$\text{Var}(\hat{\beta}_1)$** 由噪声方差和 $X$ 的分散程度共同决定
6. **模型诊断**通过残差来检查假设——我们只能"不拒绝"假设，无法"接受"
7. **t 检验和 p 值**用于判断回归系数是否显著异于零
8. **$R^2$** 衡量模型解释了多少 $Y$ 的变异
9. **预测时需谨慎外推**——离数据范围越远，预测越不可靠
